import { useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { toast } from "sonner";
import { FileUpload } from "@/components/shared/FileUpload";
import { Banner } from "@/components/shared/Banner";
import { FieldWrapper } from "@/components/shared/FieldWrapper";
import { SectionCard, SectionLabel } from "@/components/shared/SectionCard";
import { StatusBadge } from "@/components/shared/StatusBadge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useStore } from "@/store/useStore";
import type { Customer, CustomerContact } from "@/types";

const AREA_OPTIONS = [
	"Nairobi",
	"Mombasa",
	"Nakuru",
	"Eldoret",
	"Kisumu",
	"Thika",
	"Nyeri",
	"Machakos",
	"Meru",
	"Kitale",
	"Athi River",
	"Naivasha",
	"Other",
];

const BLANK_CONTACT: CustomerContact = {
	id: "",
	name: "",
	role: "",
	area: "Nairobi",
	phone: "",
	email: "",
	isPrimary: false,
};

const BLANK: Omit<Customer, "id" | "status" | "createdBy" | "approvedBy"> = {
	name: "",
	registeredName: "",
	group: "Miller",
	kraPin: "",
	address: "",
	creditLimit: 0,
	exposureLimit: 0,
	guarantee: "",
	moistureRule: "",
	fmRule: "",
	offloadingBorneBy: "Customer",
	contacts: [
		{
			id: "CT-1",
			name: "",
			role: "Procurement Manager",
			area: "Nairobi",
			phone: "",
			email: "",
			isPrimary: true,
		},
	],
};

export default function CustomerDetailPage() {
	const { id } = useParams<{ id: string }>();
	const navigate = useNavigate();
	const isNew = id === "new";
	
	const customers = useStore((s) => s.customers);
	const existing = useStore((s) => (isNew ? undefined : s.customers.find((x) => x.id === id)));
	const createCustomer = useStore((s) => s.createCustomer);
	const updateCustomer = useStore((s) => s.updateCustomer);
	const submitCustomerForVerification = useStore((s) => s.submitCustomerForVerification);
	const approveCustomer = useStore((s) => s.approveCustomer);

	// Auto generated Customer ID
	const autogeneratedId = isNew ? `CUS-${String(customers.length + 1).padStart(4, "0")}` : (existing?.id ?? "");

	const [form, setForm] = useState<Omit<Customer, "id" | "status" | "createdBy" | "approvedBy">>(() => {
		if (existing) {
			const { id: _i, status: _s, createdBy: _c, approvedBy: _a, ...rest } = existing;
			return { ...rest, contacts: existing.contacts || BLANK.contacts };
		}
		return BLANK;
	});
	const [errors, setErrors] = useState<Record<string, string>>({});

	if (!isNew && !existing) {
		return <div className="rounded-lg border border-dashed p-8 text-center text-muted-foreground">Customer not found.</div>;
	}

	const status = existing?.status ?? "Draft";

	function set<K extends keyof typeof form>(key: K, value: (typeof form)[K]) {
		setForm((f) => ({ ...f, [key]: value }));
	}

	// Contact person helpers
	function addContact() {
		const newContact: CustomerContact = {
			...BLANK_CONTACT,
			id: `CT-${Date.now()}`,
			isPrimary: form.contacts.length === 0,
		};
		set("contacts", [...form.contacts, newContact]);
	}

	function updateContact(index: number, field: keyof CustomerContact, value: any) {
		const updated = form.contacts.map((c, i) => {
			if (i === index) {
				return { ...c, [field]: value };
			}
			if (field === "isPrimary" && value === true) {
				return { ...c, isPrimary: false };
			}
			return c;
		});
		set("contacts", updated);
	}

	function removeContact(index: number) {
		if (form.contacts.length <= 1) {
			toast.error("At least one contact person is required");
			return;
		}
		const updated = form.contacts.filter((_, i) => i !== index);
		if (!updated.some((c) => c.isPrimary) && updated.length > 0) {
			updated[0].isPrimary = true;
		}
		set("contacts", updated);
	}

	function validate(): boolean {
		const next: Record<string, string> = {};
		if (!form.name) next.name = "Customer name is required";
		setErrors(next);
		return Object.keys(next).length === 0;
	}

	function handleSave() {
		if (!validate()) {
			toast.error("Customer name is required");
			return;
		}
		if (isNew) {
			const created = createCustomer({ ...form, id: autogeneratedId });
			toast.success(`Customer ${created.id} created as Draft`);
			navigate(`/customers/${created.id}`);
		} else if (existing) {
			updateCustomer(existing.id, form);
			toast.success("Changes saved");
		}
	}

	function handleVerify() {
		if (!existing) return;
		updateCustomer(existing.id, form);
		submitCustomerForVerification(existing.id);
		toast.success("Submitted for verification");
	}

	function handleApprove() {
		if (!existing) return;
		approveCustomer(existing.id);
		toast.success("Customer approved — active & ready for sales");
	}

	return (
		<div>
			{/* Top Header & Status */}
			<div className="mb-4 flex items-start justify-between">
				<div>
					<h1 className="text-xl font-semibold tracking-tight">{isNew ? "New Customer" : existing!.name}</h1>
					<p className="text-sm font-mono text-muted-foreground">ID: {autogeneratedId} (Auto-generated)</p>
				</div>
				<div className="flex items-center gap-2">
					{!isNew && <StatusBadge status={status} />}
					{status === "Approved" ? (
						<span className="inline-flex items-center rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-800">
							Active in Sales
						</span>
					) : (
						<span className="inline-flex items-center rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-800">
							Inactive in Sales (Approval Required)
						</span>
					)}
				</div>
			</div>

			{/* Status Banners for Customer Activation */}
			{!isNew && status === "Draft" && (
				<div className="mb-4">
					<Banner type="warn">
						Customer is currently in <strong>Draft</strong>. Only <strong>Approved</strong> customers are active and can be selected when selling.
					</Banner>
				</div>
			)}
			{!isNew && status === "Verified" && (
				<div className="mb-4">
					<Banner type="info">
						Customer is <strong>Verified</strong> and pending Manager/Finance approval before becoming active for selling.
					</Banner>
				</div>
			)}
			{!isNew && status === "Approved" && (
				<div className="mb-4">
					<Banner type="ok">
						Customer is <strong>Approved</strong> by {existing!.approvedBy}. Active and ready to be selected for sales & invoicing.
					</Banner>
				</div>
			)}

			{/* Basic Details */}
			<SectionLabel>Basic details</SectionLabel>
			<SectionCard>
				<div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
					{/* Auto-generated Customer ID Field (Read-only, non-editable) */}
					<FieldWrapper label="Customer ID (Auto-generated)">
						<Input
							value={autogeneratedId}
							readOnly
							disabled
							className="bg-muted font-mono text-sm cursor-not-allowed text-muted-foreground font-semibold"
						/>
						<p className="mt-1 text-[11px] text-muted-foreground">Auto-generated system ID (non-editable)</p>
					</FieldWrapper>

					<FieldWrapper label="Customer Name" required error={errors.name}>
						<Input
							value={form.name}
							onChange={(e) => set("name", e.target.value)}
							placeholder="e.g. Pembe Flour Mills Ltd"
						/>
					</FieldWrapper>

					<FieldWrapper label="Registered Name (per KRA)">
						<Input
							value={form.registeredName || ""}
							onChange={(e) => set("registeredName", e.target.value)}
							placeholder="Auto-filled via OCR or edit manually"
						/>
					</FieldWrapper>

					<FieldWrapper label="Customer Group">
						<Select value={form.group} onValueChange={(v) => set("group", v as Customer["group"])}>
							<SelectTrigger className="w-full"><SelectValue placeholder="Select group…" /></SelectTrigger>
							<SelectContent>
								{["Miller", "Exporter", "Feed Manufacturer", "Trader"].map((o) => (
									<SelectItem key={o} value={o}>{o}</SelectItem>
								))}
							</SelectContent>
						</Select>
					</FieldWrapper>

					<FieldWrapper label="KRA Certificate (OCR Upload)">
						<FileUpload
							onFile={(file) => {
								if (file) {
									toast.info("Extracting details via OCR...");
									setTimeout(() => {
										const extractedPin = "P051667788F";
										const extractedRegName = "PEMBE FLOUR MILLS LIMITED";
										const extractedAddress = "Plot 42, Industrial Area, Athi River";
										set("kraPin", extractedPin);
										set("registeredName", extractedRegName);
										if (!form.name) set("name", "Pembe Flour Mills Ltd");
										set("address", extractedAddress);
										toast.success("OCR auto-filled KRA PIN & Registered Name! All fields can be manually overwritten.");
									}, 500);
								}
							}}
						/>
					</FieldWrapper>

					<FieldWrapper label="KRA PIN (Auto-filled / Edit manually)">
						<Input
							value={form.kraPin}
							onChange={(e) => set("kraPin", e.target.value.toUpperCase())}
							placeholder="e.g. P051667788F"
						/>
					</FieldWrapper>

					<FieldWrapper label="Address">
						<Input
							value={form.address}
							onChange={(e) => set("address", e.target.value)}
							placeholder="e.g. Athi River, Machakos"
						/>
					</FieldWrapper>
				</div>

				<div className="mt-4 rounded-md border border-blue-100 bg-blue-50/50 p-3 text-xs text-blue-700">
					⚡ <strong>OCR Mapped Fields:</strong> KRA PIN, Registered Name, Customer Name, and Address are auto-populated via OCR upload. All fields allow full manual overwrite.
				</div>
			</SectionCard>

			{/* Contact Persons Section (Point 3: Tag each customer contact person with an area) */}
			<SectionLabel>Contact persons (Tagged with Area)</SectionLabel>
			<SectionCard>
				<p className="mb-3 text-xs text-muted-foreground">
					Add key contact persons for this customer and assign an <strong>Area</strong> dropdown tag to each contact.
				</p>
				
				<div className="overflow-x-auto rounded-md border">
					<table className="w-full text-left text-sm">
						<thead className="bg-muted/50 text-xs font-semibold text-muted-foreground">
							<tr>
								<th className="px-3 py-2.5">No.</th>
								<th className="px-3 py-2.5">Contact Name</th>
								<th className="px-3 py-2.5">Role</th>
								<th className="px-3 py-2.5">Area (Dropdown Tag)</th>
								<th className="px-3 py-2.5">Phone</th>
								<th className="px-3 py-2.5">Email</th>
								<th className="px-3 py-2.5 text-center">Primary</th>
								<th className="px-3 py-2.5 text-right">Action</th>
							</tr>
						</thead>
						<tbody className="divide-y">
							{form.contacts.map((contact, index) => (
								<tr key={contact.id || index} className="hover:bg-muted/20">
									<td className="px-3 py-2 text-xs font-medium text-muted-foreground">{index + 1}</td>
									<td className="px-3 py-2">
										<Input
											className="h-8 text-xs"
											value={contact.name}
											placeholder="Contact Name"
											onChange={(e) => updateContact(index, "name", e.target.value)}
										/>
									</td>
									<td className="px-3 py-2">
										<Input
											className="h-8 text-xs"
											value={contact.role}
											placeholder="Role (e.g. Finance)"
											onChange={(e) => updateContact(index, "role", e.target.value)}
										/>
									</td>
									<td className="px-3 py-2 min-w-[150px]">
										<Select
											value={contact.area}
											onValueChange={(val) => updateContact(index, "area", val)}
										>
											<SelectTrigger className="h-8 text-xs w-full">
												<SelectValue placeholder="Select Area" />
											</SelectTrigger>
											<SelectContent>
												{AREA_OPTIONS.map((area) => (
													<SelectItem key={area} value={area} className="text-xs">
														{area}
													</SelectItem>
												))}
											</SelectContent>
										</Select>
									</td>
									<td className="px-3 py-2">
										<Input
											className="h-8 text-xs font-mono"
											value={contact.phone}
											placeholder="07XX XXX XXX"
											onChange={(e) => updateContact(index, "phone", e.target.value)}
										/>
									</td>
									<td className="px-3 py-2">
										<Input
											className="h-8 text-xs"
											value={contact.email}
											placeholder="email@company.co.ke"
											onChange={(e) => updateContact(index, "email", e.target.value)}
										/>
									</td>
									<td className="px-3 py-2 text-center">
										<input
											type="radio"
											name="primaryContact"
											checked={contact.isPrimary}
											onChange={() => updateContact(index, "isPrimary", true)}
											className="h-4 w-4 cursor-pointer accent-primary"
										/>
									</td>
									<td className="px-3 py-2 text-right">
										<Button
											type="button"
											variant="ghost"
											size="sm"
											className="h-7 text-xs text-destructive hover:text-destructive"
											onClick={() => removeContact(index)}
										>
											Remove
										</Button>
									</td>
								</tr>
							))}
						</tbody>
					</table>
				</div>

				<div className="mt-3 flex justify-between items-center">
					<Button type="button" variant="outline" size="sm" onClick={addContact} className="text-xs">
						+ Add contact person
					</Button>
					<span className="text-xs text-muted-foreground">
						Tagging contacts with an area ensures localized communication & dispatch logistics.
					</span>
				</div>
			</SectionCard>

			{/* Commercial Terms (Point 4: Payment terms dropdown field removed) */}
			<SectionLabel>Commercial terms</SectionLabel>
			<SectionCard>
				<div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
					<FieldWrapper label="Credit limit (KES)">
						<Input
							type="number"
							value={form.creditLimit}
							onChange={(e) => set("creditLimit", Number(e.target.value) || 0)}
						/>
					</FieldWrapper>

					<FieldWrapper label="Exposure limit (KES)">
						<Input
							type="number"
							value={form.exposureLimit}
							onChange={(e) => set("exposureLimit", Number(e.target.value) || 0)}
						/>
					</FieldWrapper>

					<FieldWrapper label="Guarantee / security held">
						<Input
							value={form.guarantee}
							onChange={(e) => set("guarantee", e.target.value)}
							placeholder="e.g. Bank Guarantee KES 5M"
						/>
					</FieldWrapper>
				</div>
			</SectionCard>

			{/* Quality Profile */}
			<SectionLabel>Quality profile</SectionLabel>
			<SectionCard>
				<div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
					<FieldWrapper label="Moisture rule">
						<Input
							value={form.moistureRule}
							onChange={(e) => set("moistureRule", e.target.value)}
							placeholder="e.g. 13.5% max"
						/>
					</FieldWrapper>

					<FieldWrapper label="Foreign matter rule">
						<Input
							value={form.fmRule}
							onChange={(e) => set("fmRule", e.target.value)}
							placeholder="e.g. 2.0% max"
						/>
					</FieldWrapper>

					<FieldWrapper label="Offloading borne by">
						<Select value={form.offloadingBorneBy} onValueChange={(v) => set("offloadingBorneBy", v as Customer["offloadingBorneBy"])}>
							<SelectTrigger className="w-full"><SelectValue placeholder="Select…" /></SelectTrigger>
							<SelectContent>
								{["Customer", "Us"].map((o) => (
									<SelectItem key={o} value={o}>{o}</SelectItem>
								))}
							</SelectContent>
						</Select>
					</FieldWrapper>
				</div>
			</SectionCard>

			{/* Form Buttons */}
			<div className="mt-6 flex flex-wrap items-center gap-2">
				<Button onClick={handleSave}>{isNew ? "Submit as Draft" : "Save changes"}</Button>
				{!isNew && status === "Draft" && <Button variant="outline" onClick={handleVerify}>Submit for verification</Button>}
				{!isNew && status === "Verified" && <Button onClick={handleApprove}>Approve Customer (Activate)</Button>}
				<Button variant="ghost" onClick={() => navigate("/customers")}>Cancel</Button>
			</div>
		</div>
	);
}
